### ISSUE TITLE
Contributor's Agreement Explained - pdf link needs fixing

### ISSUE THREAD

**Issue by tulikavijay** [plone/documentation#954]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
[Contributor's Agreement Explained](https://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html) contains a link to the agreement's pdf which actually links to https://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html#id1

* **What is the expected behavior?**
The correct link should be shown which is https://plone.org/foundation/contributors-agreement/agreement.pdf

**Comment by svx** [comment]
This is already fixed on GitHub ?

@tulikavijay is is really nice that you are reporting things, just a suggestion it may be worth to check first if a issue is already reported :)

Thanks !

**Comment by tulikavijay** [comment]
Thanks for the reply, I'll keep that in mind!
I did not see the comments on issue#942. i did'nt know it was resolved, it still shows the link?

**Comment by svx** [comment]
@tulikavijay #942 is fixed, too.

The issues are still open, because there was still no sync with docs.plone.org.

The next sync will be done in **a week**, and then all this issues will be closed.
